---
- hosts: localhost
  vars:
    test_prefix: ansible-integration-test
  tasks:
    - name: list test projects
      equinix.cloud.metal_project_info:
        filters:
          name: "{{ test_prefix }}"
      register: test_projects
    
    - name: list devices in test projects
      equinix.cloud.metal_device_info:
        project_id: "{{ item.id }}"
      register: "test_devices"
      loop: "{{ test_projects.resources }}"

    - name: delete test devices
      equinix.cloud.metal_device:
        id: "{{ item.id }}"
        state: absent
      ignore_errors: yes
      loop: "{{ test_devices.results | map(attribute='resources') | flatten }}"

    - name: delete test projects
      equinix.cloud.metal_project:
        id: "{{ item.id }}"
        state: absent
      ignore_errors: yes
      loop: "{{ test_projects.resources }}"
