#!/usr/bin/python
# -*- coding: utf-8 -*-

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# DOCUMENTATION, EXAMPLES, and RETURN are generated by
# ansible_specdoc. Do not edit them directly.

DOCUMENTATION = '''
author: Equinix DevRel Team (@equinix) <support@equinix.com>
description: Manage project ssh key in Equinix Metal. Read more about personal and
  project SSH keys in [Equinix Metal documentation](https://deploy.equinix.com/developers/docs/metal/accounts/ssh-keys/#personal-keys-vs-project-keys).
  You can use *id* or *label* to lookup a project SSH key. If you want to create new
  resource, you must provide *label*, *key* and *project_id*.
module: metal_project_ssh_key
notes: []
options:
  id:
    description:
    - UUID of the ssh_key.
    required: false
    type: str
  key:
    description:
    - The public key of the project ssh_key.
    required: false
    type: str
  label:
    description:
    - The name of the ssh_key.
    required: false
    type: str
  project_id:
    description:
    - The ID of parent project.
    required: false
    type: str
requirements: null
short_description: Manage a project ssh key in Equinix Metal
'''
EXAMPLES = '''
- name: Create new project project ssh_key
  hosts: localhost
  tasks:
  - equinix.cloud.metal_project_ssh_key:
      label: test_key
      key: ssh-dss AAAAB3NzaC1kc3MAAACBAPLEVntPO3L7VUbEwWZ2ErkQJ3KJ8o9kFXJrPcpvVfdNag4jIhQDqbtAUgUy6BclhhbfH9l5nlGTprrpEFkxm/GL91qJUX6xrPkDMjMqx2wSKa4YraReOrCOfkqqEkC3o3G/gYSuvTzLgp2rmPiflypftZyzNM4JZT8jDwFGotJhAAAAFQDPk43bayONtUxjkAcOf+6zP1qb6QAAAIBZHHH0tIlth5ot+Xa/EYuB/M4qh77EkrWUbER0Kki7suskw/ffdKQ0y/v+ZhoAHtBU7BeE3HmP98Vrha1i4cOU+A7DCqV+lK/a+5LoEpua0M2M+VzNSGluYuV4qGpAOxNh3mxUi2R7yXxheN1oks1ROJ/bqkF4BJQXU9Nv49GkZgAAAIByWcsFeOitvzyDaNJOZzEHv9fqGuj0L3maRVWb6O47HGzlMzniIy8WjL2dfgm2/ek+NxVR/yFnYTKDPr6+0uqSD/cb4eHaFbIj7v+k7H8hA1Ioz+duJ1ONAjn6KwneXxOXu15bYIR49P7Go0s9jCdSAP/r9NE5TnE3yiRiQzgEzw==
        tomk@node
      project_id: b8c6c653-3c96-446e-987e-9c4d12f25353
- name: Remove project ssh_key by id
  hosts: localhost
  tasks:
  - equinix.cloud.metal_project_ssh_key:
      id: eef49903-7a09-4ca1-af67-4087c29ab5b6
      state: absent
'''
RETURN = '''
metal_project_ssh_key:
  description: The module object
  returned: always
  sample:
  - "\n{\n  \"fingerprint\": \"98:9c:35:ed:f9:75:5b:52:e2:70:50:22:ea:77:5b:b6\",\n\
    \  \"id\": \"eef49903-7a09-4ca1-af67-4087c29ab5b6\",\n  \"key\": \"ssh-dss AAAAB4NzaC1kc3MAAACBAPLEVntPO3L7VUbEwWZ2ErkQJ3KJ8o9kFXJrPcpvVfdNag4jIhQDqbtAUgUy6BclhhbfH9l5nlGTprrpEFkxm/GL91qJUX6xrPkDMjMqx2wSKa4YraReOrCOfkqqEkC3o3G/gYSuvTzLgp2rmPiflypftZyzNM4JZT8jDwFGotJhAAAAFQDPk43bayONtUxjkAcOf+6zP1qb6QAAAIBZHHH0tIlth5ot+Xa/EYuB/M4qh77EkrWUbER0Kki7suskw/ffdKQ0y/v+ZhoAHtBU7BeE3HmP98Vrha1i4cOU+A7DCqV+lK/a+5LoEpua0M2M+VzNSGluYuV4qGpAOxNh3mxUi2R7yXxheN1oks1ROJ/bqkF4BJQXU9Nv49GkZgAAAIByWcsFeOitvzyDaNJOZzEHv9fqGuj0L3maRVWb6O47HGzlMzniIy8WjL2dfgm2/ek+NxVR/yFnYTKDPr6+0uqSD/cb4eHaFbIj7v+k7H8hA1Ioz+duJ1ONAjn6KwneXxOXu15bYIR49P7Go0s9jCdSAP/r9NE5TnE3yiRiQzgEzw==\
    \ tomk@xps\",\n  \"label\": \"test_key\",\n  \"project_id\": \"b8c6c653-3c96-446e-987e-9c4d12f25353\"\
    \n}\n"
  type: dict
'''

# End of generated documentation

from ansible.module_utils._text import to_native
from ansible_specdoc.objects import (
    SpecField,
    FieldType,
    SpecReturnValue,
)
import traceback

from ansible_collections.equinix.cloud.plugins.module_utils.equinix import (
    EquinixModule,
    get_diff,
    getSpecDocMeta,
)


MODULE_NAME = "metal_project_ssh_key"
METAL_SSH_KEY = "metal_ssh_key"

module_spec = dict(
    id=SpecField(
        type=FieldType.string,
        description=["UUID of the ssh_key."],
    ),
    label=SpecField(
        type=FieldType.string,
        description=["The name of the ssh_key."],
        editable=True,
    ),
    key=SpecField(
        type=FieldType.string,
        description=["The public key of the project ssh_key."],
        editable=True,
    ),
    project_id=SpecField(
        type=FieldType.string,
        description=["The ID of parent project."],
        editable=True,
    ),
)


specdoc_examples = [
    """
- name: Create new project project ssh_key
  hosts: localhost
  tasks:
  - equinix.cloud.metal_project_ssh_key:
      label: "test_key"
      key: "ssh-dss AAAAB3NzaC1kc3MAAACBAPLEVntPO3L7VUbEwWZ2ErkQJ3KJ8o9kFXJrPcpvVfdNag4jIhQDqbtAUgUy6BclhhbfH9l5nlGTprrpEFkxm/GL91qJUX6xrPkDMjMqx2wSKa4YraReOrCOfkqqEkC3o3G/gYSuvTzLgp2rmPiflypftZyzNM4JZT8jDwFGotJhAAAAFQDPk43bayONtUxjkAcOf+6zP1qb6QAAAIBZHHH0tIlth5ot+Xa/EYuB/M4qh77EkrWUbER0Kki7suskw/ffdKQ0y/v+ZhoAHtBU7BeE3HmP98Vrha1i4cOU+A7DCqV+lK/a+5LoEpua0M2M+VzNSGluYuV4qGpAOxNh3mxUi2R7yXxheN1oks1ROJ/bqkF4BJQXU9Nv49GkZgAAAIByWcsFeOitvzyDaNJOZzEHv9fqGuj0L3maRVWb6O47HGzlMzniIy8WjL2dfgm2/ek+NxVR/yFnYTKDPr6+0uqSD/cb4eHaFbIj7v+k7H8hA1Ioz+duJ1ONAjn6KwneXxOXu15bYIR49P7Go0s9jCdSAP/r9NE5TnE3yiRiQzgEzw== tomk@node"
      project_id: "b8c6c653-3c96-446e-987e-9c4d12f25353"
""",
    """
- name: Remove project ssh_key by id
  hosts: localhost
  tasks:
  - equinix.cloud.metal_project_ssh_key:
      id: "eef49903-7a09-4ca1-af67-4087c29ab5b6"
      state: absent
""",
]

result_sample = [
    """
{
  "fingerprint": "98:9c:35:ed:f9:75:5b:52:e2:70:50:22:ea:77:5b:b6",
  "id": "eef49903-7a09-4ca1-af67-4087c29ab5b6",
  "key": "ssh-dss AAAAB4NzaC1kc3MAAACBAPLEVntPO3L7VUbEwWZ2ErkQJ3KJ8o9kFXJrPcpvVfdNag4jIhQDqbtAUgUy6BclhhbfH9l5nlGTprrpEFkxm/GL91qJUX6xrPkDMjMqx2wSKa4YraReOrCOfkqqEkC3o3G/gYSuvTzLgp2rmPiflypftZyzNM4JZT8jDwFGotJhAAAAFQDPk43bayONtUxjkAcOf+6zP1qb6QAAAIBZHHH0tIlth5ot+Xa/EYuB/M4qh77EkrWUbER0Kki7suskw/ffdKQ0y/v+ZhoAHtBU7BeE3HmP98Vrha1i4cOU+A7DCqV+lK/a+5LoEpua0M2M+VzNSGluYuV4qGpAOxNh3mxUi2R7yXxheN1oks1ROJ/bqkF4BJQXU9Nv49GkZgAAAIByWcsFeOitvzyDaNJOZzEHv9fqGuj0L3maRVWb6O47HGzlMzniIy8WjL2dfgm2/ek+NxVR/yFnYTKDPr6+0uqSD/cb4eHaFbIj7v+k7H8hA1Ioz+duJ1ONAjn6KwneXxOXu15bYIR49P7Go0s9jCdSAP/r9NE5TnE3yiRiQzgEzw== tomk@xps",
  "label": "test_key",
  "project_id": "b8c6c653-3c96-446e-987e-9c4d12f25353"
}
"""
]

MUTABLE_ATTRIBUTES = [k for k, v in module_spec.items() if v.editable]

SPECDOC_META = getSpecDocMeta(
    short_description="Manage a project ssh key in Equinix Metal",
    description=(
        "Manage project ssh key in Equinix Metal. "
        "Read more about personal and project SSH keys in [Equinix Metal documentation](https://deploy.equinix.com/developers/docs/metal/accounts/ssh-keys/#personal-keys-vs-project-keys). "
        "You can use *id* or *label* to lookup a project SSH key. "
        "If you want to create new resource, you must provide *label*, *key* and *project_id*."
    ),
    examples=specdoc_examples,
    options=module_spec,
    return_values={
        MODULE_NAME: SpecReturnValue(
            description="The module object",
            type=FieldType.dict,
            sample=result_sample,
        ),
    },
)


def main():
    module = EquinixModule(
        argument_spec=SPECDOC_META.ansible_spec,
        required_one_of=[("label", "id")],
        required_together=[("label", "key")],
    )
    state = module.params.get("state")
    changed = False

    try:
        module.params_syntax_check()
        if module.params.get("id"):
            tolerate_not_found = state == "absent"
            fetched = module.get_by_id(METAL_SSH_KEY, tolerate_not_found)
        else:
            fetched = module.get_one_from_list(
                MODULE_NAME,
                ["key"],
            )

        if fetched:
            module.params["id"] = fetched["id"]
            if state == "present":
                diff = get_diff(module.params, fetched, MUTABLE_ATTRIBUTES)
                if diff:
                    fetched = module.update_by_id(diff, METAL_SSH_KEY)
                    changed = True

            else:
                module.delete_by_id(METAL_SSH_KEY)
                changed = True
        else:
            if state == "present":
                fetched = module.create(MODULE_NAME)
                changed = True
            else:
                fetched = {}
    except Exception as e:
        tb = traceback.format_exc()
        module.fail_json(msg=f"Error in {MODULE_NAME}: {to_native(e)}", exception=tb)

    fetched.update({"changed": changed})
    module.exit_json(**fetched)


if __name__ == "__main__":
    main()
