#!/usr/bin/python
# -*- coding: utf-8 -*-

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# DOCUMENTATION, EXAMPLES, and RETURN are generated by
# ansible_specdoc. Do not edit them directly.

DOCUMENTATION = ""
EXAMPLES = ""
RETURN = ""

# End

from ansible.module_utils._text import to_native
from ansible_specdoc.objects import SpecField, FieldType, SpecReturnValue
import traceback

from ansible_collections.equinix.cloud.plugins.module_utils.equinix import (
    EquinixModule,
    getSpecDocMeta,
)

module_spec = dict(
    project_id=SpecField(
        type=FieldType.string,
        description=['UUID of parent project the gateway is scoped to.'],
    ),
)

specdoc_examples = ['''
- name: Gather information about all gateways in parent project
  hosts: localhost
  tasks:
      - equinix.cloud.metal_gateway_info
          project_id: 2a5122b9-c323-4d5c-b53c-9ad3f54273e7
''', '''
''',
                    ]

result_sample = ['''

[  
  {
    "id": "31d3ae8b-bd5a-41f3-a420-055211345cc7",
    "virtual_network_id": "eef49903-7a09-4ca1-af67-4087c29ab5b6",
    "project_id": "845b45a3-c565-47e5-b9b6-a86204a73d29",
    "private_ipv4_subnet_size": 32
  }
]''',
]

SPECDOC_META = getSpecDocMeta(
    short_description="Gather information about Equinix Metal gateways",
    description=(
        'Gather information about Equinix Metal gateways'
    ),
    examples=specdoc_examples,
    options=module_spec,
    return_values={
        "resources": SpecReturnValue(
            description='Found gateways',
            type=FieldType.dict,
            sample=result_sample,
        ),
    },
)


def main():
    module = EquinixModule(
        argument_spec=SPECDOC_META.ansible_spec,
        is_info=True,
    )
    try:
        module.params_syntax_check()
        return_value = {'resources': module.get_list("metal_gateway")}
    except Exception as e:
        tr = traceback.format_exc()
        module.fail_json(msg=to_native(e), exception=tr)
    module.exit_json(**return_value)


if __name__ == '__main__':
    main()
